version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "55000:6333"  # REST API
      - "55001:6334"  # GRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__STORAGE__WAL_CAPACITY_MB=2048  # Allocate 2GB for Write-Ahead Log
      - QDRANT__STORAGE__STORAGE_SIZE_MB=20480  # Allocate 20GB for storage
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:6333/healthz", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/qdrant_data
      o: bind
