name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 55000:6333
          - 55001:6334
        env:
          QDRANT__STORAGE__WAL_CAPACITY_MB: 512
          QDRANT__STORAGE__STORAGE_SIZE_MB: 4096
        options: >-
          --health-cmd "curl -f http://localhost:6333/healthz"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 5s

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run tests with coverage
      env:
        QDRANT_HOST: localhost
        QDRANT_PORT: 55000
        KEBOOLA_TOKEN: dummy-token
        KEBOOLA_API_URL: https://dummy.keboola.com
      run: |
        pytest tests/ --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 